# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e3698ab2b4028e4ccd5513e0c55dc454f9cbeac72de8be650e49790b3e1e0881fa3ddb139fce7cdfece7a5740d9f55542a8f617d539a80ea0f25ed80bf894a

test:
  secret_key_base: 4960927d8901172b5476d5ba9e386f66bf5e74eb9f2e1e9ed50bf5539bbaf255d69bf97ca87692af2b97184272f1d1a6e18bbb58c6e596bab3e0675fb00bb4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
